version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - /home/ec2-user/config/code-hub/application.properties:/app/config/application.properties
    command: [ "java", "-jar", "app.jar", "--spring.config.location=file:/app/config/application.properties" ]
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins:jdk17
#    ports:
#      - "8888:8080"         # Jenkins 웹 UI
#      - "50000:50000"       # 에이전트 커넥션 포트
#    volumes:
#      - jenkins_home:/var/jenkins_home
#    restart: unless-stopped
#volumes:
#  jenkins_home: